/*
*
* Copyright 2016
* All rights reserved.
* This file is automatically generated by python script of which 
* the author is kevinmeng.
*
*/

namespace game_level_auto{

	class game_level_cfg_t
	{

		void load(el::lib_file_tab_txt_t& file_tab_txt, std::vector<std::string>& ref){
			std::string __str_def__;		
		}
	};
}
